services:
  reporter-sync:
    image: privxsshcom/privx-reporter-sync:latest
    container_name: reporter-sync
    restart: unless-stopped
    depends_on:
      reporter-data-db:
        condition: service_healthy
      reporter-admin-db:
        condition: service_healthy
    networks:
      - reporter-shared-network
    environment:
      ENV_SOURCE: ${ENV_SOURCE}

      DB_DATA_HOST: reporter-data-db
      DB_DATA_PORT: 5432
      DB_DATA_NAME: ${DB_DATA_NAME}
      DB_DATA_USER: ${DB_DATA_USER}
      DB_DATA_PASSWORD: ${DB_DATA_PASSWORD}
      DB_DATA_SSL_MODE: ${DB_DATA_SSL_MODE}

      DB_ADMIN_HOST: reporter-admin-db
      DB_ADMIN_PORT: 5432
      DB_ADMIN_NAME: ${DB_ADMIN_NAME}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE}

  reporter-backup:
    build:
      context: .
      dockerfile: Dockerfile-backup
    container_name: reporter-backup
    restart: unless-stopped
    depends_on:
      reporter-data-db:
        condition: service_healthy
      reporter-admin-db:
        condition: service_healthy
    networks:
      - reporter-shared-network
    volumes:
      - ${BACKUP_DIR}:${BACKUP_DIR}
    environment:
      ENV_SOURCE: ${ENV_SOURCE}
      BACKUP_DIR: ${BACKUP_DIR}

      DB_DATA_HOST: reporter-data-db
      DB_DATA_PORT: 5432
      DB_DATA_NAME: ${DB_DATA_NAME}
      DB_DATA_USER: ${DB_DATA_USER}
      DB_DATA_PASSWORD: ${DB_DATA_PASSWORD}
      DB_DATA_SSL_MODE: ${DB_DATA_SSL_MODE}

      DB_ADMIN_HOST: reporter-admin-db
      DB_ADMIN_PORT: 5432
      DB_ADMIN_NAME: ${DB_ADMIN_NAME}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE}

  reporter-ui:
    image: privxsshcom/privx-reporter-ui:latest
    container_name: reporter-ui
    restart: unless-stopped
    depends_on:
      reporter-data-db:
        condition: service_healthy
      reporter-admin-db:
        condition: service_healthy
    ports:
      - 8501:8501
    volumes:
      - ${REPORT_OUT_DIR}:/root/reports
    networks:
      - reporter-shared-network
    environment:
      ENV_SOURCE: ${ENV_SOURCE}
      
      SSL_CERT: /opt/reporter/certs/fullchain.pem
      SSL_KEY: /opt/reporter/certs/privatekey.pem

      DB_DATA_HOST: reporter-data-db
      DB_DATA_PORT: 5432
      DB_DATA_NAME: ${DB_DATA_NAME}
      DB_DATA_USER: ${DB_DATA_USER}
      DB_DATA_PASSWORD: ${DB_DATA_PASSWORD}
      DB_DATA_SSL_MODE: ${DB_DATA_SSL_MODE}

      DB_ADMIN_HOST: reporter-admin-db
      DB_ADMIN_PORT: 5432
      DB_ADMIN_NAME: ${DB_ADMIN_NAME}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE}

  reporter-data-db:
    image: timescale/timescaledb:latest-pg18
    container_name: reporter-data-db
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/usr/local/bin/pg_ssl_entry_point.sh"]
    command: >
      postgres
      -c ssl=${DB_DATA_SSL_MODE:-off}
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
      -c ssl_key_file=/var/lib/postgresql/certs/server.key
      -c hba_file=/var/lib/postgresql/certs/pg_hba.conf
    ports:
      - ${DB_DATA_PORT:-5454}:5432
    environment:
      POSTGRES_USER: ${DB_DATA_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_DATA_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATA_NAME:-report_data}
    volumes:
      - /opt/reporter/.volumes/data-db:/var/lib/postgresql
      - ./.pg-ssl:/certs-src:ro
      - ./.pg-ssl/pg_ssl_entry_point.sh:/usr/local/bin/pg_ssl_entry_point.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reporter-shared-network

  reporter-admin-db:
    image: postgres:18
    container_name: reporter-admin-db
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/usr/local/bin/pg_ssl_entry_point.sh"]
    command: >
      postgres
      -c ssl=${DB_ADMIN_SSL_MODE:-off}
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
      -c ssl_key_file=/var/lib/postgresql/certs/server.key
      -c hba_file=/var/lib/postgresql/certs/pg_hba.conf
    ports:
      - ${DB_ADMIN_PORT:-5455}:5432
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_ADMIN_NAME:-report_admin}
    volumes:
      - /opt/reporter/.volumes/admin-db:/var/lib/postgresql
      - ./.pg-ssl:/certs-src:ro
      - ./.pg-ssl/pg_ssl_entry_point.sh:/usr/local/bin/pg_ssl_entry_point.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reporter-shared-network

networks:
  reporter-shared-network:
    name: reporter-shared-network
