[list.subcommands.secrets]
help = "Query secrets by various filtering"

[list.subcommands.secrets.options.name]
flags = ["--name"]
required = false
help = "Filter by secret name (case-insensitive substring match)"

[list.subcommands.secrets.options.read_role]
flags = ["--read-role"]
required = false
help = "Filter by read role name (case-insensitive substring match)"

[list.subcommands.secrets.options.write_role]
flags = ["--write-role"]
required = false
help = "Filter by write role name (case-insensitive substring match)"
